import { StyleSheet } from "react-native";

export const temporizadorStyles = StyleSheet.create({
  modalBackground: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  modalContainer: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },
  exerciseName: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#91766E",
    marginBottom: 4,
  },
  repetitionCount: {
    fontSize: 14,
    color: "#666",
    marginBottom: 20,
  },
  timerText: {
    fontSize: 40,
    fontWeight: "bold",
    color: "#000",
  },
  phaseTextCentered: {
    fontSize: 18,
    color: "#5C3B3B",
    marginTop: 16,
    fontWeight: "500",
  },
  controlsRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    marginTop: 30,
    width: "90%",
    gap: 12,
  },
  circleButton: {
    width: 56,
    height: 56,
    backgroundColor: "#C8A19C",
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 5,
  },
  inputsRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: 24,
    width: "100%",
    paddingHorizontal: 20,
  },
  inputGroup: {
    alignItems: "center",
  },
  inputLabel: {
    fontSize: 14,
    color: "#5C3B3B",
    marginBottom: 6,
  },
  timeInput: {
    width: 90,
    height: 42,
    borderColor: "#C8A19C",
    borderWidth: 1.5,
    borderRadius: 12,
    textAlign: "center",
    fontSize: 16,
    color: "#000",
    backgroundColor: "#F3ECE3",
  },
  botaoSalvar: {
    marginTop: 24,
    flexDirection: "row",
    backgroundColor: "#91766E",
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    gap: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  botaoSalvarTexto: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "bold",
  },
});
