import { Platform, StyleSheet } from "react-native";
import { fonts } from "../../../theme/fonts";
import { palette } from "../../../theme/colors";

export const timerReplicaStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#FCFAF7" },
  header: { height: 82, paddingHorizontal: 25, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  back: { width: 46, height: 46, borderRadius: 23, alignItems: "center", justifyContent: "center", backgroundColor: "#F0E8F2" },
  brand: { position: "absolute", left: 90, right: 90, alignItems: "center" },
  brandName: { fontFamily: fonts.title, fontSize: 31, lineHeight: 34, color: palette.purpleDark },
  tagline: { fontFamily: fonts.bodyMedium, fontSize: 6, letterSpacing: 2.7, color: "#827487" },
  endHeader: { fontFamily: fonts.bodyBold, fontSize: 15, color: palette.purpleDark },
  content: { flex: 1, alignItems: "center", paddingHorizontal: 25, paddingBottom: 70 },
  title: { fontFamily: fonts.bodyBold, fontSize: 29, lineHeight: 35, color: palette.purpleDark, textAlign: "center", marginTop: 13 },
  repetition: { fontFamily: fonts.body, fontSize: 17, color: "#757080", marginTop: 5 },
  ringWrap: { marginTop: 18, alignItems: "center", justifyContent: "center" },
  ringInner: { alignItems: "center" },
  remaining: { fontFamily: fonts.bodyMedium, fontSize: 11, letterSpacing: 2.3, color: "#7A778A" },
  timer: { fontFamily: fonts.bodyBold, fontSize: 58, lineHeight: 67, color: palette.purpleDark, marginTop: 8 },
  divider: { width: 58, height: 1, backgroundColor: "#DEDBD8", marginTop: 4 },
  phase: { fontFamily: fonts.bodyMedium, fontSize: 17, color: "#567C4A", marginTop: 10 },
  metrics: { width: "100%", flexDirection: "row", gap: 7, marginTop: 14 },
  metric: { flex: 1, height: 53, borderRadius: 16, borderWidth: 1, borderColor: "#E2DFDA", backgroundColor: "rgba(255,255,255,.65)", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, paddingHorizontal: 7 },
  metricLabel: { fontFamily: fonts.body, fontSize: 9, color: "#79727F" },
  metricValue: { fontFamily: fonts.bodyBold, fontSize: 11, color: palette.purpleDark },
  tipCard: { width: "100%", height: 134, borderRadius: 20, borderWidth: 1, borderColor: "#E2DFDA", backgroundColor: "rgba(255,255,255,.7)", padding: 12, flexDirection: "row", gap: 14, marginTop: 10 },
  photo: { width: 112, height: 110, borderRadius: 14, resizeMode: "cover", backgroundColor: "#E8DFD9" },
  tipCopy: { flex: 1, justifyContent: "center" },
  tipBadge: { alignSelf: "flex-start", paddingHorizontal: 14, paddingVertical: 4, borderRadius: 15, backgroundColor: "#E9F0E4", fontFamily: fonts.bodyBold, fontSize: 9, letterSpacing: 1.6, color: "#5B7851" },
  tipText: { fontFamily: fonts.body, fontSize: 14, lineHeight: 19, color: palette.purpleDark, marginTop: 9 },
  controls: { width: "100%", flexDirection: "row", justifyContent: "space-around", marginTop: 5, paddingBottom: 35 },
  control: { flex: 1, alignItems: "center", gap: 3 },
  controlCircle: { width: 50, height: 50, borderRadius: 25, alignItems: "center", justifyContent: "center", backgroundColor: "#F0EAF2" },
  controlPrimary: { backgroundColor: palette.purpleDark },
  controlLabel: { fontFamily: fonts.bodyMedium, fontSize: 10, lineHeight: 13, color: palette.purpleDark, textAlign: "center" },
  motivation: { position: "absolute", left: 24, right: 24, bottom: 69, height: 32, borderRadius: 17, backgroundColor: "#EDF4E8", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 14 },
  motivationText: { fontFamily: fonts.bodyMedium, fontSize: 10, color: "#527449" },
  bottomNav: { position: "absolute", left: 0, right: 0, bottom: 0, height: 70, paddingBottom: Platform.OS === "ios" ? 7 : 2, borderTopLeftRadius: 24, borderTopRightRadius: 24, backgroundColor: "#FFFCFA", flexDirection: "row", borderTopWidth: 1, borderTopColor: "#EEE6ED", elevation: 10 },
  navItem: { flex: 1, alignItems: "center", justifyContent: "center", gap: 1 },
  navText: { fontFamily: fonts.body, fontSize: 10, color: "#706687" },
  navActive: { fontFamily: fonts.bodyBold, color: palette.purpleDark },
  navDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: palette.purpleDark },
  editPanel: { position: "absolute", left: 30, right: 30, bottom: 174, borderRadius: 20, padding: 18, backgroundColor: "#fff", elevation: 12 },
  editRow: { flexDirection: "row", justifyContent: "space-around" },
  editGroup: { alignItems: "center" },
  editLabel: { fontFamily: fonts.body, fontSize: 11, color: "#716A75", marginBottom: 5 },
  editInput: { width: 82, height: 40, borderWidth: 1, borderColor: "#DCCFDF", borderRadius: 12, textAlign: "center", color: palette.purpleDark },
  save: { height: 42, borderRadius: 21, backgroundColor: palette.purple, alignItems: "center", justifyContent: "center", marginTop: 14 },
  saveText: { fontFamily: fonts.bodyBold, color: "#fff" },
});
