import { StyleSheet } from "react-native";
import { palette } from "../../theme/colors";

export const luniaStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    justifyContent: "center",
    alignItems: "center",
  },
  container: {
    alignItems: "center",
    paddingHorizontal: 24,
    width: "100%",
  },
  logo: {
    width: 90,
    height: 90,
    resizeMode: "contain",
    marginBottom: -10,
    zIndex: 10,
  },
  balao: {
    backgroundColor: palette.bgSoft,
    borderRadius: 20,
    paddingVertical: 20,
    paddingHorizontal: 24,
    width: "85%",
    position: "relative",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 5,
    zIndex: 1,
  },
  triangulo: {
    position: "absolute",
    top: -12,
    left: 32,
    width: 0,
    height: 0,
    borderLeftWidth: 12,
    borderRightWidth: 12,
    borderBottomWidth: 14,
    borderStyle: "solid",
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    borderBottomColor: palette.bgSoft,
  },
  titulo: {
    fontSize: 16,
    color: palette.textPrimary,
    marginBottom: 8,
    textAlign: "center",
  },
  bold: {
    fontWeight: "bold",
  },
  texto: {
    fontSize: 14,
    color: palette.textPrimary,
    textAlign: "center",
    lineHeight: 22,
  },
  botoes: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 20,
    gap: 12,
  },
  botaoRosa: {
    backgroundColor: palette.textSecondary,
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 12,
  },
  textoBotaoRosa: {
    color: palette.white,
    fontWeight: "600",
    fontSize: 14,
  },
  botaoVerde: {
    backgroundColor: palette.sage,
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 12,
  },
  textoBotaoVerde: {
    color: palette.white,
    fontWeight: "600",
    fontSize: 14,
  },
  fecharAbsoluto: {
    position: "absolute",
    top: 0,
    right: 0,
    backgroundColor: palette.white,
    borderRadius: 16,
    width: 22,
    height: 22,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
    zIndex: 10,
  },
  fecharTexto: {
    fontSize: 14,
    color: palette.purpleLight,
    fontWeight: "bold",
    textAlign: "center",
    lineHeight: 18,
  },
});
