import { StyleSheet } from "react-native";
import { palette } from "../../theme/colors";
import { fonts } from "../../theme/fonts";

/**
 * Rotina de cuidados — mesma linguagem das telas de Kegel e da Lunia: header
 * com wordmark, cards claros com borda lilás, chips arredondados e a barra
 * inferior. Verde marca o que foi feito; bronze, o que ficou atrasado.
 */
export const rotinaStyles = StyleSheet.create({
  screen: { flex: 1, paddingHorizontal: 18 },
  center: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24 },
  scroll: { flex: 1 },
  scrollContent: { paddingBottom: 18, gap: 12 },

  // ------------------------------------------------------------------ header
  header: { height: 62, justifyContent: "center", alignItems: "center" },
  back: {
    position: "absolute",
    left: 3,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#F0E7F2",
    alignItems: "center",
    justifyContent: "center",
  },
  backPressed: { backgroundColor: "#E5D7EA" },
  brand: { alignItems: "center" },
  brandName: { fontFamily: fonts.title, fontSize: 31, lineHeight: 33, color: palette.purpleDark },
  brandTag: { fontFamily: fonts.bodyMedium, fontSize: 6, letterSpacing: 2.8, color: "#786C84" },

  // ------------------------------------------------------------------ título
  tituloLinha: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12 },
  titulo: { fontFamily: fonts.title, fontSize: 32, lineHeight: 36, color: palette.purpleDark },
  subtitulo: { fontFamily: fonts.body, fontSize: 14, color: "#766C8C", marginTop: 2 },
  frase: { width: 88, fontFamily: fonts.title, fontSize: 11, lineHeight: 14, textAlign: "center", color: "#405344" },

  // ------------------------------------------------------------------- cards
  card: {
    borderWidth: 1,
    borderColor: "#E6D7E8",
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,.72)",
    padding: 14,
  },
  cardLilas: { backgroundColor: "rgba(239,223,241,.83)" },
  cardVerde: { borderColor: "#C7DCBB", backgroundColor: "rgba(240,246,235,.9)" },
  linha: { flexDirection: "row", alignItems: "center", gap: 10 },
  linhaEntre: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  secaoTitulo: { fontFamily: fonts.title, fontSize: 19, color: palette.purpleDark },
  link: { flexDirection: "row", alignItems: "center", gap: 1 },
  linkTexto: { fontFamily: fonts.bodyMedium, fontSize: 12, color: palette.purple },

  pillData: {
    height: 46,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#EDE4E9",
    backgroundColor: "rgba(255,253,250,.9)",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  pillDataTexto: { flex: 1, fontFamily: fonts.bodyMedium, fontSize: 13, color: palette.textPrimary },
  pillDataContagem: { fontFamily: fonts.body, fontSize: 12, color: palette.purple },

  // ----------------------------------------------------------------- próximo
  proximoIcone: {
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: "#DFCBE5",
    alignItems: "center",
    justifyContent: "center",
  },
  proximoIconeVerde: { backgroundColor: "#DDEBD3" },
  proximoRotulo: { fontFamily: fonts.body, fontSize: 12, color: "#6E6580" },
  proximoNome: { fontFamily: fonts.title, fontSize: 23, lineHeight: 27, color: palette.purpleDark },
  proximoDose: { fontFamily: fonts.body, fontSize: 12, color: "#6D647B" },
  botaoTomei: {
    height: 38,
    borderRadius: 19,
    paddingHorizontal: 13,
    backgroundColor: palette.purpleDark,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  botaoTomeiTexto: { fontFamily: fonts.bodyBold, fontSize: 12, color: "#fff" },

  // ------------------------------------------------------------------- doses
  doseLinha: { flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 9 },
  doseSeparador: { borderTopWidth: 1, borderTopColor: "#F0E8F1" },
  doseHora: { width: 42, fontFamily: fonts.bodyMedium, fontSize: 13, color: palette.textPrimary },
  doseCopy: { flex: 1, minWidth: 0 },
  doseNome: { fontFamily: fonts.bodySemiBold, fontSize: 14, color: palette.textPrimary },
  doseDetalhe: { fontFamily: fonts.body, fontSize: 11, color: "#6D647B" },
  alertaEstoque: { fontFamily: fonts.bodyMedium, fontSize: 10, color: palette.warning, marginTop: 1 },
  status: {
    minWidth: 96,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  statusTomado: { backgroundColor: "#EDF5E8", borderColor: "#C7DCBB" },
  statusPendente: { backgroundColor: "#F4EBF5", borderColor: "#E6D7E8" },
  statusAtrasado: { backgroundColor: "#F6EEE6", borderColor: "#E3D2BF" },
  statusTexto: { fontFamily: fonts.bodyMedium, fontSize: 11 },

  // -------------------------------------------------------------------- água
  aguaValor: { fontFamily: fonts.title, fontSize: 27, lineHeight: 31, color: palette.purpleDark },
  aguaMeta: { fontFamily: fonts.body, fontSize: 13, color: "#6D647B" },
  botoesAgua: { flexDirection: "row", gap: 7 },
  botaoAgua: {
    flex: 1,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#DCCAE2",
    backgroundColor: "#F4EBF5",
    alignItems: "center",
    justifyContent: "center",
  },
  botaoAguaGrande: { height: 50, borderRadius: 25 },
  botaoAguaTexto: { fontFamily: fonts.bodyBold, fontSize: 12, color: palette.purpleDark },
  botaoAguaTextoGrande: { fontSize: 16 },
  anelCentro: { alignItems: "center" },
  anelValor: { fontFamily: fonts.title, fontSize: 42, lineHeight: 46, color: palette.purpleDark },
  anelMeta: { fontFamily: fonts.body, fontSize: 13, color: "#6D647B" },
  registro: { flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 8 },
  registroTexto: { flex: 1, fontFamily: fonts.bodyMedium, fontSize: 13, color: palette.textPrimary },
  registroHora: { fontFamily: fonts.body, fontSize: 12, color: "#6D647B" },
  lembreteChip: {
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E6D7E8",
    backgroundColor: "rgba(255,255,255,.7)",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  sequenciaIcone: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#F6EEE6",
    alignItems: "center",
    justifyContent: "center",
  },
  sequenciaValor: { fontFamily: fonts.title, fontSize: 22, lineHeight: 26, color: palette.purpleDark },
  stepper: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "#F0E7F2",
    alignItems: "center",
    justifyContent: "center",
  },
  metaValor: { fontFamily: fonts.title, fontSize: 30, color: palette.purpleDark },

  // ------------------------------------------------------------------- lunia
  lunia: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: 18,
    backgroundColor: "rgba(239,223,241,.6)",
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  luniaTexto: { fontFamily: fonts.titleItalic, fontSize: 14, lineHeight: 19, color: palette.purpleDark },
  luniaLegenda: { fontFamily: fonts.body, fontSize: 11, color: "#6D647B", marginTop: 2 },

  // ------------------------------------------------------------------ botões
  botaoPrimario: {
    height: 54,
    borderRadius: 27,
    backgroundColor: palette.purpleDark,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  botaoPrimarioTexto: { fontFamily: fonts.bodyBold, fontSize: 15, color: "#fff" },
  botaoSecundario: {
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#DCCAE2",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  botaoSecundarioTexto: { fontFamily: fonts.bodyMedium, fontSize: 14, color: palette.purpleDark },
  botaoPerigoTexto: { color: palette.error },
  desabilitado: { opacity: 0.55 },

  vazioTitulo: { fontFamily: fonts.title, fontSize: 20, color: palette.purpleDark, textAlign: "center" },
  vazioTexto: { fontFamily: fonts.body, fontSize: 13, color: "#6D647B", textAlign: "center", marginTop: 4 },

  // -------------------------------------------------------------- formulário
  campo: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  campoIcone: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#F0E7F2",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  campoCorpo: { flex: 1, minWidth: 0, gap: 6 },
  rotulo: { fontFamily: fonts.bodySemiBold, fontSize: 13, color: palette.textPrimary },
  ajuda: { fontFamily: fonts.body, fontSize: 11, lineHeight: 15, color: "#6D647B" },
  input: {
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E4DED2",
    backgroundColor: palette.glass,
    paddingHorizontal: 12,
    fontFamily: fonts.body,
    fontSize: 14,
    color: palette.textPrimary,
  },
  inputMultilinha: { minHeight: 76, paddingTop: 10, textAlignVertical: "top" },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 7 },
  chip: {
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#DCCAE2",
    backgroundColor: "rgba(255,255,255,.6)",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  chipAtivo: { backgroundColor: palette.purpleDark, borderColor: palette.purpleDark },
  chipTexto: { fontFamily: fonts.bodyMedium, fontSize: 12, color: palette.purpleDark },
  chipTextoAtivo: { color: "#fff" },
  chipAdicionar: { width: 36, paddingHorizontal: 0, justifyContent: "center" },
  dias: { flexDirection: "row", justifyContent: "space-between", gap: 4 },
  dia: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#DCCAE2",
    backgroundColor: "rgba(255,255,255,.6)",
    alignItems: "center",
    justifyContent: "center",
  },
  diaAtivo: { backgroundColor: palette.purpleDark, borderColor: palette.purpleDark },
  diaTexto: { fontFamily: fonts.bodyBold, fontSize: 12, color: palette.purpleDark },
  diaTextoAtivo: { color: "#fff" },
  datas: { flexDirection: "row", gap: 10 },
  dataCampo: { flex: 1, minWidth: 0, gap: 6 },
  dataBotao: {
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E4DED2",
    backgroundColor: palette.glass,
    paddingHorizontal: 11,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  dataTexto: { flex: 1, fontFamily: fonts.body, fontSize: 13, color: palette.textPrimary },
  dataPlaceholder: { color: palette.textMuted },
  interruptor: { flexDirection: "row", alignItems: "center", gap: 12 },
  estoqueLinha: { flexDirection: "row", gap: 10, paddingLeft: 56 },

  // --------------------------------------------------------------- histórico
  alternador: { flexDirection: "row", borderRadius: 18, backgroundColor: "#F1E8F2", padding: 3, alignSelf: "flex-start" },
  alternadorOpcao: { height: 32, borderRadius: 16, paddingHorizontal: 16, justifyContent: "center" },
  alternadorAtivo: { backgroundColor: palette.purpleDark },
  alternadorTexto: { fontFamily: fonts.bodyMedium, fontSize: 12, color: palette.purpleDark },
  alternadorTextoAtivo: { color: "#fff" },
  metricas: { flexDirection: "row", gap: 8 },
  metrica: {
    flex: 1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E6D7E8",
    backgroundColor: "rgba(255,255,255,.72)",
    padding: 11,
    gap: 2,
  },
  metricaValor: { fontFamily: fonts.title, fontSize: 22, lineHeight: 26, color: palette.purpleDark },
  metricaRotulo: { fontFamily: fonts.body, fontSize: 10, lineHeight: 13, color: "#6D647B" },
  grafico: { flexDirection: "row", alignItems: "flex-end", gap: 3, marginTop: 12 },
  barraColuna: { flex: 1, alignItems: "center", gap: 4 },
  barraTrilho: {
    width: "100%",
    maxWidth: 22,
    height: 84,
    borderRadius: 6,
    backgroundColor: "#F1E8F2",
    justifyContent: "flex-end",
    overflow: "hidden",
  },
  barraPreenchida: { width: "100%", borderRadius: 6 },
  barraRotulo: { fontFamily: fonts.body, fontSize: 9, color: "#6D647B", height: 12 },
  progresso: { flex: 1, height: 7, borderRadius: 4, backgroundColor: "#EDE2EF", overflow: "hidden" },
  progressoPreenchido: { height: "100%", borderRadius: 4, backgroundColor: palette.purple },

  // ----------------------------------------------------------- barra inferior
  bottomNav: {
    height: 67,
    marginHorizontal: -18,
    marginTop: 7,
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: "#EDE4E9",
    backgroundColor: "rgba(255,252,250,.95)",
    borderTopLeftRadius: 23,
    borderTopRightRadius: 23,
  },
  navItem: { flex: 1, alignItems: "center", justifyContent: "center", gap: 1 },
  navText: { fontFamily: fonts.body, fontSize: 9, color: "#756D89" },

  // ------------------------------------------------------------------ modais
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(56,35,62,.45)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 22,
  },
  modalCard: {
    width: "100%",
    maxHeight: "88%",
    borderRadius: 24,
    backgroundColor: "#FFFCFA",
    borderWidth: 1,
    borderColor: "#E6D7E8",
    padding: 20,
  },
  modalTitulo: { fontFamily: fonts.title, fontSize: 25, color: palette.purpleDark },
  modalSubtitulo: { fontFamily: fonts.body, fontSize: 12, color: "#6E6580", marginTop: 3, marginBottom: 12 },
  modalBotoes: { flexDirection: "row", gap: 10, marginTop: 16 },
});
