import { StyleSheet } from "react-native";
import { fonts } from "../../theme/fonts";
import { palette } from "../../theme/colors";

export const cycleStyles = StyleSheet.create({
  safe: { flex: 1 }, header: { height: 76, paddingHorizontal: 22, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, headerCompact: { height: 68 }, headerDense: { height: 60 }, back: { width: 43, height: 43, borderRadius: 22, backgroundColor: "#F0E7F2", alignItems: "center", justifyContent: "center" }, headerSpacer: { width: 43 }, brand: { position: "absolute", left: 88, right: 88, alignItems: "center" }, brandName: { fontFamily: fonts.title, fontSize: 30, lineHeight: 32, color: palette.purpleDark }, brandTagline: { fontFamily: fonts.bodyMedium, fontSize: 6, letterSpacing: 2.7, color: "#7F7188" },
  content: { paddingHorizontal: 19, paddingBottom: 76, gap: 11 }, titleBlock: { height: 95, position: "relative", paddingTop: 1, paddingHorizontal: 5 }, title: { fontFamily: fonts.title, fontSize: 38, lineHeight: 42, color: palette.purpleDark }, subtitle: { maxWidth: "76%", fontFamily: fonts.body, fontSize: 13, lineHeight: 16, color: "#716A8A", marginTop: 2 }, sideMessage: { position: "absolute", right: 2, top: -4, width: 73, alignItems: "center" }, sideMessageText: { fontFamily: fonts.title, fontSize: 12, lineHeight: 14, color: "#425044", textAlign: "center" },
  contentCompact: { paddingHorizontal: 19, paddingBottom: 66, gap: 8 }, contentDense: { paddingHorizontal: 14, paddingBottom: 60, gap: 6 }, titleBlockCompact: { height: 92 }, titleBlockDense: { height: 72 },
  titleCompact: { fontSize: 34, lineHeight: 39 }, titleDense: { fontSize: 29, lineHeight: 33 }, subtitleCompact: { fontSize: 11, lineHeight: 15, marginTop: 2 }, subtitleDense: { fontSize: 9, lineHeight: 12, marginTop: 1 }, sideMessageDense: { top: -2 }, sideMessageTextDense: { fontSize: 9, lineHeight: 11 },
  phaseCard: { height: 90, borderRadius: 18, backgroundColor: "#F1E3F1", borderWidth: 1, borderColor: "#E4D2E5", flexDirection: "row", alignItems: "center", paddingHorizontal: 11, paddingVertical: 8, shadowColor: palette.purpleDark, shadowOffset: { width: 0, height: 4 }, shadowOpacity: .04, shadowRadius: 10, elevation: 1 }, phaseIcon: { width: 58, height: 58, borderRadius: 29, backgroundColor: "#E3D0E7", alignItems: "center", justifyContent: "center" }, phaseCopy: { flex: 1, minWidth: 0, paddingLeft: 11, justifyContent: "center" }, phaseLabel: { fontFamily: fonts.body, fontSize: 12, lineHeight: 16, color: "#665B70" }, phaseLine: { fontFamily: fonts.body, fontSize: 11, color: palette.purpleDark }, phaseStrong: { fontFamily: fonts.bodyBold, fontSize: 13, color: palette.purpleDark }, cycleDay: { fontFamily: fonts.bodyMedium, fontSize: 12, lineHeight: 16, color: palette.purpleDark }, phaseCaption: { fontFamily: fonts.body, fontSize: 9, lineHeight: 12, color: "#746A86", marginTop: 3 }, phaseDivider: { width: 1, height: 58, marginHorizontal: 8, backgroundColor: "#CDB7D0" }, nextPeriod: { width: 124, minHeight: 68, borderRadius: 16, backgroundColor: "rgba(255,255,255,.52)", paddingHorizontal: 8, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 4 }, nextPeriodCopy: { flex: 1, minWidth: 0 }, nextPeriodLabel: { fontFamily: fonts.body, fontSize: 8, lineHeight: 10, color: "#665B73" }, nextPeriodValue: { fontFamily: fonts.bodyBold, fontSize: 11, lineHeight: 13, color: palette.purpleDark },
  phaseCardCompact: { height: 82 }, phaseCardDense: { height: 70 },
  calendarCard: { height: 365, borderRadius: 21, borderWidth: 1, borderColor: "#E5DFE2", backgroundColor: "rgba(255,255,255,.78)", paddingHorizontal: 10, paddingTop: 9, shadowColor: palette.purpleDark, shadowOffset: { width: 0, height: 5 }, shadowOpacity: .04, shadowRadius: 12, elevation: 1 }, monthHeader: { height: 45, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, monthButton: { width: 38, height: 38, borderRadius: 19, backgroundColor: "#F6F1F5", alignItems: "center", justifyContent: "center" }, monthTitle: { fontFamily: fonts.bodyBold, fontSize: 19, color: palette.purpleDark }, weekdays: { flexDirection: "row", height: 27, alignItems: "center" }, weekday: { width: "14.285%", textAlign: "center", fontFamily: fonts.bodyBold, fontSize: 9, color: "#736A87" }, grid: { flexDirection: "row", flexWrap: "wrap" }, dayCell: { width: "14.285%", height: 43, alignItems: "center", justifyContent: "center" }, dayCircle: { width: 35, height: 35, borderRadius: 18, backgroundColor: "#F0E8F1", alignItems: "center", justifyContent: "center" }, dayText: { fontFamily: fonts.body, fontSize: 12, color: palette.purpleDark }, today: { borderWidth: 2, borderColor: palette.purpleDark, backgroundColor: "#F5E9C9" }, legend: { position: "absolute", left: 10, right: 10, bottom: 8, height: 34, borderRadius: 14, backgroundColor: "#F4EDF3", flexDirection: "row", alignItems: "center", justifyContent: "space-around" }, legendItem: { flexDirection: "row", alignItems: "center", gap: 4 }, legendDot: { width: 17, height: 17, borderRadius: 9, borderWidth: 1 }, dotted: { borderWidth: 2, borderStyle: "dotted" }, legendText: { fontFamily: fonts.body, fontSize: 8, color: "#5F566F" },
  calendarCardCompact: { height: 330 }, calendarCardDense: { height: 275 }, dayCellCompact: { height: 38 }, dayCellDense: { height: 31 }, dayCircleCompact: { width: 32, height: 32, borderRadius: 16 }, dayCircleDense: { width: 27, height: 27, borderRadius: 14 },
  insightCard: { height: 174, borderRadius: 20, borderWidth: 1, borderColor: "#E5DFE2", backgroundColor: "rgba(255,255,255,.72)", padding: 12, overflow: "hidden" }, todayPill: { alignSelf: "flex-start", height: 25, borderRadius: 13, backgroundColor: "#EEE3EF", paddingHorizontal: 13, flexDirection: "row", alignItems: "center" }, todayStrong: { fontFamily: fonts.bodyBold, fontSize: 11, color: palette.purpleDark }, todayDate: { fontFamily: fonts.body, fontSize: 10, color: "#655C72" }, insightBody: { flexDirection: "row", marginTop: 8 }, bulb: { width: 44, height: 44, borderRadius: 22, backgroundColor: "#F0EAF3", alignItems: "center", justifyContent: "center" }, insightCopy: { flex: 1, paddingLeft: 10, paddingRight: 80 }, insightTitle: { fontFamily: fonts.title, fontSize: 17, lineHeight: 20, color: palette.purpleDark }, insightText: { fontFamily: fonts.body, fontSize: 10, lineHeight: 13, color: "#716A80", marginTop: 3 }, lunia: { position: "absolute", width: 95, height: 80, resizeMode: "contain", right: -5, bottom: -26 }, insightMetrics: { position: "absolute", left: 12, right: 12, bottom: 10, height: 40, flexDirection: "row", gap: 7 }, insightMetric: { flex: 1, borderWidth: 1, borderColor: "#E3DAE5", borderRadius: 18, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6, backgroundColor: "#FAF7FA" }, insightMetricText: { fontFamily: fonts.body, fontSize: 9, color: "#665C70" }, insightMetricStrong: { fontFamily: fonts.bodyBold, color: palette.purpleDark },
  symptomsCard: { minHeight: 105, borderRadius: 20, borderWidth: 1, borderColor: "#E2D6E3", backgroundColor: "#FBF6FA", padding: 15, flexDirection: "row", alignItems: "center", gap: 13 }, symptomsIcon: { width: 53, height: 53, borderRadius: 27, backgroundColor: "#EADDED", alignItems: "center", justifyContent: "center" }, symptomsCopy: { flex: 1 }, symptomsOverline: { fontFamily: fonts.bodyBold, fontSize: 8, letterSpacing: 1.5, color: "#927E96" }, symptomsTitle: { fontFamily: fonts.title, fontSize: 18, lineHeight: 21, color: palette.purpleDark, marginTop: 2 }, symptomsText: { fontFamily: fonts.body, fontSize: 10, lineHeight: 13, color: "#756D7B", marginTop: 3 }, symptomsArrow: { width: 37, height: 37, borderRadius: 19, backgroundColor: palette.purple, alignItems: "center", justifyContent: "center" },
  symptomsCardCompact: { minHeight: 88, paddingVertical: 10 }, symptomsCardDense: { minHeight: 72, paddingVertical: 7 },
  bottomNav: { position: "absolute", left: 0, right: 0, bottom: 0, height: 70, borderTopLeftRadius: 24, borderTopRightRadius: 24, backgroundColor: "#FFFCFA", flexDirection: "row", borderTopWidth: 1, borderTopColor: "#ECE4EA", elevation: 10 }, navItem: { flex: 1, alignItems: "center", justifyContent: "center", gap: 1 }, navText: { fontFamily: fonts.body, fontSize: 10, color: "#756D89" }, navActive: { fontFamily: fonts.bodyBold, color: palette.purpleDark }, navDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: palette.purpleDark },
  bottomNavCompact: { height: 64 }, bottomNavDense: { height: 58 },
});
