import { Platform, StyleSheet } from "react-native";
import { fonts } from "../../theme/fonts";
import { palette } from "../../theme/colors";

export const treinoStyles = StyleSheet.create({
  safeArea: { flex: 1 },
  header: { height: 76, paddingHorizontal: 24, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  circleButton: { width: 42, height: 42, borderRadius: 21, alignItems: "center", justifyContent: "center", backgroundColor: "#EDE2EF" },
  settingsButton: { backgroundColor: "#ECEAE7" },
  headerSpacer: { width: 42, height: 42 },
  brand: { position: "absolute", left: 90, right: 90, alignItems: "center" },
  brandName: { fontFamily: fonts.title, fontSize: 30, lineHeight: 33, color: palette.purpleDark },
  brandTagline: { fontFamily: fonts.bodyMedium, fontSize: 7, letterSpacing: 3, color: "#89788E" },
  content: { paddingHorizontal: 22, paddingBottom: 62 },
  intro: { height: 130, paddingTop: 4 },
  overline: { fontFamily: fonts.bodyMedium, fontSize: 10, letterSpacing: 2.8, color: "#49444E" },
  phaseTitle: { fontFamily: fonts.title, fontSize: 29, lineHeight: 33, color: palette.purpleDark, marginTop: 2 },
  workoutName: { fontFamily: fonts.bodyBold, fontSize: 16, color: palette.purpleDark },
  description: { fontFamily: fonts.body, fontSize: 11, lineHeight: 14, color: "#77717E", marginTop: 6, maxWidth: "61%" },
  mascotBadge: { position: "absolute", right: 2, top: 15, width: 115, height: 112, alignItems: "center", justifyContent: "center" },
  luniaImage: { width: 106, height: 80, resizeMode: "contain", marginTop: 13 },
  moon: { position: "absolute", right: 15, top: 0 },
  mascotText: { fontFamily: fonts.titleItalic, fontSize: 13, color: "#765F74", transform: [{ rotate: "-9deg" }] },
  metricsRow: { flexDirection: "row", gap: 7, marginBottom: 9 },
  metric: { flex: 1, minWidth: 0, height: 50, borderRadius: 13, borderWidth: 1, borderColor: "#E4DFDC", backgroundColor: "rgba(255,255,255,.5)", paddingHorizontal: 7, flexDirection: "row", alignItems: "center", gap: 5 },
  metricCopy: { flex: 1, minWidth: 0 },
  metricValue: { fontFamily: fonts.bodyBold, fontSize: 11, color: "#272431" },
  metricLabel: { fontFamily: fonts.body, fontSize: 8, color: "#85808A", marginTop: 3 },
  startButton: { height: 46, borderRadius: 17, backgroundColor: palette.purple, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 12, shadowColor: palette.purpleDark, shadowOffset: { width: 0, height: 5 }, shadowOpacity: .15, shadowRadius: 10, elevation: 4 },
  startButtonText: { fontFamily: fonts.bodyBold, fontSize: 16, color: "#fff" },
  sectionHeader: { height: 38, marginTop: 3, marginBottom: 2, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  sectionTitle: { fontFamily: fonts.bodyBold, fontSize: 16, color: palette.purpleDark },
  sectionProgress: { width: 155, alignItems: "flex-end" },
  sectionCount: { fontFamily: fonts.body, fontSize: 12, color: "#77717E", marginBottom: 7 },
  progressTrack: { width: "100%", height: 9, borderRadius: 6, backgroundColor: "#E5DFE6", overflow: "hidden" },
  progressFill: { height: "100%", borderRadius: 6, backgroundColor: "#8C628D" },
  exerciseCard: { height: 196, borderRadius: 18, backgroundColor: "rgba(255,255,255,.9)", padding: 10, paddingBottom: 48, marginBottom: 6, flexDirection: "row", gap: 11, shadowColor: "#57465B", shadowOffset: { width: 0, height: 4 }, shadowOpacity: .07, shadowRadius: 10, elevation: 2 },
  exerciseNumber: { position: "absolute", zIndex: 2, left: 8, top: 8, width: 38, height: 38, borderRadius: 20, backgroundColor: "#EADDEF", borderWidth: 5, borderColor: "#fff", alignItems: "center", justifyContent: "center" },
  exerciseNumberDone: { backgroundColor: palette.purple },
  exerciseNumberText: { fontFamily: fonts.bodyBold, fontSize: 13, color: palette.purpleDark },
  exerciseImage: { width: "32%", maxWidth: 116, height: 137, borderRadius: 11, backgroundColor: "#E8DFD9", overflow: "hidden", alignItems: "center", justifyContent: "center" },
  exercisePhoto: { width: "100%", height: "100%", resizeMode: "cover" },
  exerciseBody: { flex: 1, minWidth: 0, paddingRight: 2 },
  exerciseTitle: { minHeight: 19, fontFamily: fonts.bodyBold, fontSize: 15, lineHeight: 18, color: palette.purpleDark, paddingRight: 40 },
  method: { alignSelf: "flex-start", marginTop: 3, marginBottom: 4, paddingVertical: 3, paddingHorizontal: 11, borderRadius: 15, backgroundColor: "#E9DDEC", fontFamily: fonts.body, fontSize: 10, color: "#74697A" },
  playButton: { position: "absolute", right: 11, top: 12, width: 38, height: 38, borderRadius: 19, backgroundColor: palette.purple, alignItems: "center", justifyContent: "center" },
  dataRow: { minHeight: 20, flexDirection: "row", alignItems: "center", gap: 5 },
  dataLabel: { width: 57, fontFamily: fonts.body, fontSize: 10, color: "#76717B" },
  dataValue: { flex: 1, fontFamily: fonts.body, fontSize: 10, color: "#30313B" },
  note: { position: "absolute", left: 10, right: 10, bottom: 7, minHeight: 38, borderRadius: 11, paddingHorizontal: 10, paddingVertical: 5, backgroundColor: "#F6F3F2", flexDirection: "row", alignItems: "center", gap: 8 },
  noteOpenArea: { flex: 1, minWidth: 0, flexDirection: "row", alignItems: "center", gap: 8 },
  noteText: { flex: 1, fontFamily: fonts.body, fontSize: 10, lineHeight: 13, color: "#77717E" },
  completionCheck: { width: 24, height: 24, borderRadius: 12, borderWidth: 2, borderColor: "#8D7B91", backgroundColor: "#fff", alignItems: "center", justifyContent: "center" },
  completionCheckDone: { borderColor: palette.purple, backgroundColor: palette.purple },
  instructionsOverlay: { flex: 1, paddingHorizontal: 24, justifyContent: "center", backgroundColor: "rgba(43,31,46,.48)" },
  instructionsModal: { borderRadius: 25, padding: 22, backgroundColor: "#FFFCFA", shadowColor: "#2E1D32", shadowOffset: { width: 0, height: 12 }, shadowOpacity: .2, shadowRadius: 24, elevation: 12 },
  instructionsHeader: { flexDirection: "row", alignItems: "center", gap: 12 },
  instructionsIcon: { width: 48, height: 48, borderRadius: 24, alignItems: "center", justifyContent: "center", backgroundColor: "#EEE3F0" },
  instructionsHeading: { flex: 1 },
  instructionsOverline: { fontFamily: fonts.bodyMedium, fontSize: 9, letterSpacing: 2, color: "#918596" },
  instructionsTitle: { fontFamily: fonts.title, fontSize: 22, lineHeight: 27, color: palette.purpleDark },
  instructionsClose: { width: 38, height: 38, borderRadius: 19, alignItems: "center", justifyContent: "center", backgroundColor: "#F2EFED" },
  instructionsText: { marginTop: 20, fontFamily: fonts.body, fontSize: 16, lineHeight: 24, color: "#615A66" },
  instructionsButton: { height: 48, marginTop: 24, borderRadius: 24, alignItems: "center", justifyContent: "center", backgroundColor: palette.purple },
  instructionsButtonText: { fontFamily: fonts.bodyBold, fontSize: 15, color: "#fff" },
  footer: { position: "absolute", left: 0, right: 0, bottom: 0, height: 70, paddingBottom: Platform.OS === "ios" ? 7 : 2, borderTopLeftRadius: 24, borderTopRightRadius: 24, backgroundColor: "rgba(255,253,252,.98)", flexDirection: "row", alignItems: "center", justifyContent: "space-around", borderTopWidth: 1, borderTopColor: "#EEE6ED", shadowColor: palette.purpleDark, shadowOffset: { width: 0, height: -5 }, shadowOpacity: .05, shadowRadius: 18, elevation: 12 },
  navItem: { flex: 1, height: 60, alignItems: "center", justifyContent: "center", gap: 1 },
  navText: { fontFamily: fonts.body, fontSize: 11, color: "#706687" },
  navTextActive: { fontFamily: fonts.bodyBold, color: palette.purpleDark },
  navDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: palette.purpleDark, marginTop: 1 },
});
