import { StyleSheet } from "react-native";

export const faseCompletaStyles = StyleSheet.create({
  botaoVoltar: {
    position: "absolute",
    top: 56,
    left: 15,
    zIndex: 10,
    paddingVertical: 10,
    paddingHorizontal: 10,
    alignSelf: "flex-start",
    backgroundColor: "rgba(146, 96, 206, 0.3)",
    borderRadius: 30,
    borderWidth: 1,
    borderColor: "rgba(146, 96, 206, 0.5)",
  },
  logoContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 30,
    marginBottom: 20,
  },
  faseTitulo: {
    fontSize: 16,
    fontWeight: "600",
    color: "#EED0FC",
    textAlign: "center",
    marginTop: 12,
    marginBottom: 4,
  },
  faseNome: {
    fontSize: 20,
    fontWeight: "700",
    color: "#FFFAC3",
    textAlign: "center",
    marginBottom: 16,
    fontFamily: "LobsterTwo_700Bold",
  },
  faseDescricao: {
    fontSize: 14,
    color: "#EED0FC",
    lineHeight: 20,
    textAlign: "justify",
    marginBottom: 24,
    padding: 16,
    borderRadius: 12,
    backgroundColor: "rgba(63, 28, 101, 0.7)",
    borderColor: "rgba(146, 96, 206, 0.4)",
    borderWidth: 1,
  },
  subtitulo: {
    fontSize: 16,
    color: "#FFFAC3",
    fontWeight: "bold",
    marginBottom: 12,
    textAlign: "center",
  },
  inputPergunta: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderColor: "rgba(146, 96, 206, 0.6)",
    borderWidth: 1,
    borderRadius: 10,
    padding: 16,
    fontSize: 15,
    color: "#EED0FC",
    minHeight: 60,
    textAlignVertical: "top",
    marginBottom: 12,
  },
  respostaContainer: {
    backgroundColor: "rgba(63, 28, 101, 0.8)",
    padding: 16,
    borderRadius: 16,
    borderColor: "rgba(146, 96, 206, 0.4)",
    borderWidth: 1,
    marginTop: 24,
    flexDirection: "row",
    gap: 10,
  },
  respostaTexto: {
    fontSize: 15,
    color: "#EED0FC",
    lineHeight: 22,
    textAlign: "justify",
    flex: 1,
  },
  botaoPergunta: {
    backgroundColor: "#9260CE",
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    marginBottom: 20,
    shadowColor: "#9260CE",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
    elevation: 6,
  },
  botaoPerguntaTexto: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
});
