import { StyleSheet } from "react-native";
import { palette } from "../../theme/colors";
import { fonts } from "../../theme/fonts";

export const faseCompletaStyles = StyleSheet.create({
  screen: { flex: 1, paddingHorizontal: 18 },
  header: { height: 76, justifyContent: "center", alignItems: "center" },
  back: { position: "absolute", left: 3, width: 44, height: 44, borderRadius: 22, overflow: "hidden", backgroundColor: "#F0E7F2", alignItems: "center", justifyContent: "center", elevation: 0 },
  backPressed: { backgroundColor: "#E5D7EA" },
  brand: { alignItems: "center" }, brandName: { fontFamily: fonts.title, fontSize: 31, lineHeight: 33, color: palette.purpleDark }, brandTag: { fontFamily: fonts.bodyMedium, fontSize: 6, letterSpacing: 2.8, color: "#786C84" },
  hero: { height: 119, flexDirection: "row", alignItems: "center", position: "relative" }, avatarHalo: { width: 137, height: 108, borderRadius: 65, backgroundColor: "rgba(233,220,237,.55)", alignItems: "center", justifyContent: "center" }, heroAvatar: { width: 132, height: 112, resizeMode: "contain" }, heroCopy: { flex: 1, paddingLeft: 10 }, heroTitle: { fontFamily: fonts.title, fontSize: 34, lineHeight: 38, color: palette.purpleDark }, heroSubtitle: { fontFamily: fonts.body, fontSize: 14, color: "#766C8C" }, onlinePill: { marginTop: 8, height: 29, borderRadius: 15, paddingHorizontal: 10, backgroundColor: "#F1E8F2", flexDirection: "row", alignItems: "center", gap: 7, alignSelf: "flex-start" }, onlineDot: { width: 11, height: 11, borderRadius: 6, backgroundColor: "#94CE73" }, onlineText: { fontFamily: fonts.body, fontSize: 10, color: "#665C73" }, sideQuote: { position: "absolute", right: 1, top: 5, width: 68, alignItems: "center" }, sideQuoteText: { fontFamily: fonts.title, fontSize: 10, lineHeight: 12, textAlign: "center", color: "#405344" },
  phaseCard: { height: 87, borderWidth: 1, borderColor: "#E6D7E8", borderRadius: 18, backgroundColor: "rgba(239,223,241,.83)", flexDirection: "row", alignItems: "center", padding: 10 }, phaseIcon: { width: 62, height: 62, borderRadius: 31, backgroundColor: "#DFCBE5", alignItems: "center", justifyContent: "center" }, phaseCopy: { flex: 1, paddingLeft: 12, minWidth: 0 }, phaseLabel: { fontFamily: fonts.body, fontSize: 11, color: "#6E6580" }, phaseName: { fontFamily: fonts.title, fontSize: 24, lineHeight: 27, color: palette.purpleDark }, phaseDescription: { fontFamily: fonts.body, fontSize: 9, color: "#6D647B", marginTop: 1 }, phaseDivider: { width: 1, height: 43, backgroundColor: "#CDB7D0", marginHorizontal: 9 }, dayPill: { height: 34, borderRadius: 17, backgroundColor: "rgba(223,200,229,.72)", paddingHorizontal: 12, justifyContent: "center" }, dayText: { fontFamily: fonts.bodyMedium, fontSize: 10, color: palette.purpleDark },
  messages: { flex: 1, marginTop: 8 }, messagesContent: { paddingVertical: 5, gap: 6 }, luniaRow: { flexDirection: "row", alignItems: "flex-start", paddingRight: 55 }, miniAvatar: { width: 42, height: 42, resizeMode: "contain", marginRight: 7 }, luniaMessageCopy: { flex: 1 }, luniaBubble: { backgroundColor: "rgba(239,228,241,.86)", borderRadius: 17, borderTopLeftRadius: 5, paddingHorizontal: 15, paddingVertical: 11 }, luniaText: { fontFamily: fonts.body, fontSize: 12, lineHeight: 17, color: "#52425F" }, messageTime: { fontFamily: fonts.body, fontSize: 9, color: "#81788F", marginTop: 3, marginLeft: 4 }, userWrap: { alignItems: "flex-end", paddingLeft: 90 }, userBubble: { backgroundColor: palette.purpleDark, borderRadius: 17, borderBottomRightRadius: 5, paddingHorizontal: 16, paddingVertical: 11 }, userText: { fontFamily: fonts.body, fontSize: 12, lineHeight: 16, color: "#fff" }, userTime: { fontFamily: fonts.body, fontSize: 9, color: "#81788F", marginTop: 3, marginRight: 3 }, check: { color: "#81699A" }, loader: { marginVertical: 16 },
  quickRow: { height: 43, flexDirection: "row", gap: 4, alignItems: "center" }, quick: { flex: 1, height: 34, borderRadius: 17, borderWidth: 1, borderColor: "#DCCAE2", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5, backgroundColor: "rgba(255,255,255,.45)", paddingHorizontal: 5 }, quickText: { fontFamily: fonts.bodyMedium, fontSize: 8, color: palette.purpleDark },
  composer: { height: 53, borderRadius: 27, backgroundColor: "rgba(255,255,255,.82)", flexDirection: "row", alignItems: "center", paddingLeft: 15, paddingRight: 5, gap: 9, shadowColor: "#6B4669", shadowOpacity: .07, shadowRadius: 10, elevation: 2 }, input: { flex: 1, fontFamily: fonts.body, fontSize: 11, color: palette.purpleDark, paddingVertical: 0 }, send: { width: 44, height: 44, borderRadius: 22, backgroundColor: palette.purpleDark, alignItems: "center", justifyContent: "center" },
  bottomNav: { height: 67, marginHorizontal: -18, marginTop: 7, flexDirection: "row", borderTopWidth: 1, borderTopColor: "#EDE4E9", backgroundColor: "rgba(255,252,250,.95)", borderTopLeftRadius: 23, borderTopRightRadius: 23 }, navItem: { flex: 1, alignItems: "center", justifyContent: "center", gap: 1 }, navText: { fontFamily: fonts.body, fontSize: 9, color: "#756D89" }, navActive: { fontFamily: fonts.bodyBold, color: palette.purpleDark }, navDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: palette.purpleDark },
});
