import { StyleSheet } from "react-native";
import { palette } from "../../theme/colors";
import { fonts } from "../../theme/fonts";

export const symptomsStyles: any = StyleSheet.create({
  screen: { flex: 1 }, content: { paddingHorizontal: 18, paddingBottom: 82, gap: 9 }, header: { height: 72, justifyContent: "center", alignItems: "center" }, back: { position: "absolute", left: 2, width: 43, height: 43, borderRadius: 22, overflow: "hidden", backgroundColor: "#F0E7F2", alignItems: "center", justifyContent: "center" }, brand: { alignItems: "center" }, brandName: { fontFamily: fonts.title, fontSize: 29, lineHeight: 31, color: palette.purpleDark }, brandTag: { fontFamily: fonts.bodyMedium, fontSize: 6, letterSpacing: 2.6, color: "#786C84" },
  titleArea: { height: 82, position: "relative", paddingLeft: 4, paddingRight: 82 }, title: { maxWidth: 270, fontFamily: fonts.title, fontSize: 31, lineHeight: 37, color: palette.purpleDark }, subtitle: { fontFamily: fonts.body, fontSize: 14, lineHeight: 18, color: "#756D8A", marginTop: 1 }, sideMessage: { position: "absolute", right: 5, top: 0, width: 72, alignItems: "center" }, sideText: { fontFamily: fonts.title, fontSize: 10, lineHeight: 12, textAlign: "center", color: "#415044" },
  phaseCard: { height: 88, borderRadius: 18, backgroundColor: "#F1E3F1", borderWidth: 1, borderColor: "#E6D5E7", flexDirection: "row", alignItems: "center", padding: 9 }, phaseIcon: { width: 57, height: 57, borderRadius: 29, backgroundColor: "#DFCDE4", alignItems: "center", justifyContent: "center" }, phaseCopy: { flex: 1, paddingLeft: 10 }, phaseLine: { fontFamily: fonts.body, fontSize: 11, color: palette.purpleDark }, phaseStrong: { fontFamily: fonts.bodyBold }, phaseDay: { fontFamily: fonts.bodyMedium, fontSize: 11, color: palette.purpleDark }, phaseCaption: { fontFamily: fonts.body, fontSize: 8, lineHeight: 10, color: "#746A83", marginTop: 2 }, divider: { width: 1, height: 51, backgroundColor: "#CAB5CD", marginHorizontal: 7 }, next: { width: 121, height: 63, borderRadius: 16, backgroundColor: "rgba(255,255,255,.52)", flexDirection: "row", alignItems: "center", justifyContent: "space-around", paddingHorizontal: 5 }, nextLabel: { fontFamily: fonts.body, fontSize: 8, lineHeight: 10, color: "#665B73" }, nextStrong: { fontFamily: fonts.bodyBold, fontSize: 11, color: palette.purpleDark },
  section: { borderRadius: 18, backgroundColor: "rgba(255,255,255,.78)", borderWidth: 1, borderColor: "#E9E1E6", padding: 10 }, sectionHead: { height: 44, flexDirection: "row", alignItems: "center" }, sectionIcon: { width: 39, height: 39, borderRadius: 20, backgroundColor: "#F0E3F2", alignItems: "center", justifyContent: "center", marginRight: 9 }, sectionCopy: { flex: 1 }, sectionTitle: { fontFamily: fonts.bodyBold, fontSize: 15, lineHeight: 19, color: palette.purpleDark }, sectionSubtitle: { fontFamily: fonts.body, fontSize: 11, lineHeight: 14, color: "#6F667F" }, countPill: { borderRadius: 14, backgroundColor: "#F3EAF4", paddingHorizontal: 10, paddingVertical: 6 }, countText: { fontFamily: fonts.bodyBold, fontSize: 10, color: palette.purpleDark }, moodGrid: { flexDirection: "row", flexWrap: "wrap", columnGap: 6, rowGap: 6, marginTop: 6 }, choice: { width: "31.5%", height: 37, borderRadius: 19, overflow: "hidden", borderWidth: 1, borderColor: "#D8CDD9", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 4, paddingHorizontal: 5, backgroundColor: "#FBF9FA" }, choiceSelected: { borderColor: "#8D58A3", backgroundColor: "#F0E1F2" }, choiceText: { flexShrink: 1, fontFamily: fonts.bodyMedium, fontSize: 10, color: palette.purpleDark }, check: { width: 18, height: 18, borderRadius: 9, backgroundColor: palette.purpleDark, alignItems: "center", justifyContent: "center" },
  groupGrid: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 7 }, groupCard: { width: "49%", minHeight: 105, borderRadius: 14, padding: 9, borderWidth: 1 }, pinkCard: { backgroundColor: "#FCF3F6", borderColor: "#F0DFE6" }, greenCard: { backgroundColor: "#F3F7EE", borderColor: "#DEE8D8" }, blueCard: { backgroundColor: "#F3F2FC", borderColor: "#E1DFF0" }, groupTitleRow: { flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 8 }, groupTitle: { fontFamily: fonts.bodyBold, fontSize: 13, lineHeight: 17, color: palette.purpleDark }, smallChoices: { flexDirection: "row", flexWrap: "wrap", gap: 6 }, smallChoice: { minHeight: 30, borderRadius: 15, borderWidth: 1, borderColor: "#D2C5D5", flexDirection: "row", alignItems: "center", paddingHorizontal: 9, gap: 4, backgroundColor: "rgba(255,255,255,.28)" }, smallText: { fontFamily: fonts.bodyMedium, fontSize: 10, lineHeight: 13, color: "#544B69" }, smallCheck: { width: 16, height: 16, borderRadius: 8, backgroundColor: palette.purpleDark, alignItems: "center", justifyContent: "center" },
  notes: { minHeight: 96, borderRadius: 17, backgroundColor: "rgba(255,255,255,.8)", borderWidth: 1, borderColor: "#E9E1E6", padding: 10, flexDirection: "row" }, notesIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: "#F0E3F2", alignItems: "center", justifyContent: "center", marginRight: 9 }, notesBody: { flex: 1 }, notesTitle: { fontFamily: fonts.bodyBold, fontSize: 14, lineHeight: 18, color: palette.purpleDark, marginBottom: 5 }, textArea: { height: 57, borderRadius: 11, backgroundColor: "#FAF7F9", borderWidth: 1, borderColor: "#D6C9D9", padding: 10, paddingRight: 42, fontFamily: fonts.body, fontSize: 12, color: palette.purpleDark, textAlignVertical: "top" }, counter: { position: "absolute", right: 8, bottom: 5, fontFamily: fonts.bodyMedium, fontSize: 9, color: "#756B82" },
  save: { height: 49, borderRadius: 13, backgroundColor: palette.purpleDark, alignItems: "center", justifyContent: "center" }, saveText: { fontFamily: fonts.bodyBold, fontSize: 14, color: "#fff" },
  bottomNav: { position: "absolute", left: 0, right: 0, bottom: 0, height: 68, flexDirection: "row", borderTopWidth: 1, borderTopColor: "#EDE4E9", backgroundColor: "#FFFCFA", borderTopLeftRadius: 23, borderTopRightRadius: 23 }, navItem: { flex: 1, alignItems: "center", justifyContent: "center", gap: 1 }, navText: { fontFamily: fonts.body, fontSize: 9, color: "#756D89" }, navActive: { fontFamily: fonts.bodyBold, color: palette.purpleDark }, navDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: palette.purpleDark },
});
