import { StyleSheet } from "react-native";

export const perfilStyles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#5C3B3B",
    textAlign: "center",
    marginBottom: 10,
  },
  title: {
    fontSize: 20,
    fontWeight: "600",
    color: "#5C3B3B",
    marginBottom: 20,
    textAlign: "center",
  },
  input: {
    backgroundColor: "#FFECEC",
    padding: 15,
    borderRadius: 12,
    marginBottom: 16,
    color: "#5C3B3B",
    fontSize: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  dateWrapper: {
    width: "100%",
    marginBottom: 20,
  },
  dateButton: {
    backgroundColor: "#C38888",
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 3,
  },
  dateButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  cicloWrapper: {
    marginBottom: 20,
    width: "100%",
  },
  label: {
    color: "#5C3B3B",
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 10,
  },
  cicloControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF5F5",
    padding: 12,
    borderRadius: 12,
  },
  cicloButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#E0A2A2",
    justifyContent: "center",
    alignItems: "center",
  },
  cicloButtonText: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "bold",
  },
  cicloValor: {
    marginHorizontal: 20,
    fontSize: 16,
    color: "#5C3B3B",
    fontWeight: "bold",
  },
  faseTexto: {
    fontSize: 16,
    color: "#5C3B3B",
    fontWeight: "600",
    textAlign: "center",
    marginTop: 10,
    marginBottom: 14,
    backgroundColor: "#FFECEC",
    padding: 12,
    borderRadius: 10,
  },
  imcTexto: {
    fontSize: 16,
    color: "#5C3B3B",
    textAlign: "center",
    marginBottom: 20,
    backgroundColor: "#FFF5F5",
    padding: 10,
    borderRadius: 10,
  },
});
