import { StyleSheet } from "react-native";

export const perfilStyles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    justifyContent: "flex-start",
    paddingTop: 20,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFFAC3",
    textAlign: "center",
    marginBottom: 10,
    fontFamily: "LobsterTwo_700Bold",
  },
  title: {
    fontSize: 20,
    fontWeight: "600",
    color: "#FFFAC3",
    marginBottom: 20,
    textAlign: "center",
  },
  input: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    padding: 15,
    borderRadius: 12,
    marginBottom: 16,
    color: "#EED0FC",
    fontSize: 16,
    borderWidth: 1,
    borderColor: "rgba(146, 96, 206, 0.5)",
  },
  dateWrapper: {
    width: "100%",
    marginBottom: 20,
  },
  dateButton: {
    backgroundColor: "#9260CE",
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#9260CE",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 4,
  },
  dateButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  cicloWrapper: {
    marginBottom: 20,
    width: "100%",
  },
  label: {
    color: "#EED0FC",
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 10,
  },
  cicloControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(63, 28, 101, 0.6)",
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(146, 96, 206, 0.4)",
  },
  cicloButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#9260CE",
    justifyContent: "center",
    alignItems: "center",
  },
  cicloButtonText: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "bold",
  },
  cicloValor: {
    marginHorizontal: 20,
    fontSize: 16,
    color: "#FFFAC3",
    fontWeight: "bold",
  },
  faseTexto: {
    fontSize: 16,
    color: "#EED0FC",
    fontWeight: "600",
    textAlign: "center",
    marginTop: 10,
    marginBottom: 14,
    backgroundColor: "rgba(63, 28, 101, 0.6)",
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(146, 96, 206, 0.4)",
  },
  imcTexto: {
    fontSize: 16,
    color: "#EED0FC",
    textAlign: "center",
    marginBottom: 20,
    backgroundColor: "rgba(63, 28, 101, 0.5)",
    padding: 10,
    borderRadius: 10,
  },
  primeiroAcessoAviso: {
    backgroundColor: "rgba(146, 96, 206, 0.3)",
    padding: 10,
    borderRadius: 8,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#9260CE",
  },
  avisoTexto: {
    color: "#FFFAC3",
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 14,
  },
});
