import { Platform, StyleSheet } from "react-native";
import { brand, elevation, palette, radius } from "../../theme/colors";
import { fonts } from "../../theme/fonts";

export const perfilStyles = StyleSheet.create({
  container: { flex: 1, padding: 24 },
  input: { backgroundColor: palette.glass, padding: 15, borderRadius: 12, marginBottom: 16 },
  cicloWrapper: { marginBottom: 20, width: "100%" },
  dateWrapper: { width: "100%", marginBottom: 20 },
  imcTexto: { fontSize: 16, color: palette.textSecondary, textAlign: "center", marginBottom: 20 },
  screen: { flex: 1 },
  scrollContent: { paddingHorizontal: 18, paddingTop: 4, paddingBottom: 108 },
  header: { minHeight: 80, alignItems: "center", justifyContent: "center" },
  backButton: { position: "absolute", left: 0, top: 20, width: 44, height: 44, alignItems: "flex-start", justifyContent: "center", zIndex: 2 },
  logo: { width: 132, height: 68, marginBottom: 0, shadowOpacity: 0 },
  intro: { marginTop: 6, marginBottom: 16 },
  title: { fontFamily: fonts.title, fontSize: Platform.OS === "ios" ? 32 : 30, lineHeight: 38, color: brand.plumDeep, letterSpacing: -0.5 },
  subtitle: { marginTop: 5, maxWidth: 520, fontFamily: fonts.body, fontSize: 14, lineHeight: 20, color: palette.textSecondary },
  primeiroAcessoAviso: { alignSelf: "flex-start", backgroundColor: palette.lilac, borderRadius: radius.pill, paddingVertical: 7, paddingHorizontal: 12, marginBottom: 10 },
  avisoTexto: { color: palette.purpleDark, fontFamily: fonts.bodySemiBold, fontSize: 12 },
  card: { backgroundColor: "rgba(255,253,250,0.88)", borderWidth: 1, borderColor: "rgba(183,154,197,0.38)", borderRadius: 17, padding: 10, marginBottom: 9, flexDirection: "row", alignItems: "flex-start", ...elevation.card },
  cardFull: { flex: 1, minWidth: 0 },
  iconCircle: { width: 40, height: 40, borderRadius: 20, backgroundColor: "rgba(233,223,240,0.72)", alignItems: "center", justifyContent: "center", marginRight: 10 },
  cardTopRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  textColumn: { flex: 1, minWidth: 0 },
  label: { color: palette.purpleDark, fontFamily: fonts.bodySemiBold, fontSize: 14, lineHeight: 18 },
  helper: { color: palette.textSecondary, fontFamily: fonts.body, fontSize: 11.5, lineHeight: 16, marginTop: 1 },
  compactInput: { width: 108, height: 44, borderRadius: 12, borderWidth: 1, borderColor: "rgba(183,154,197,0.55)", backgroundColor: "rgba(255,255,255,0.56)", flexDirection: "row", alignItems: "center", paddingHorizontal: 11 },
  numberInput: { flex: 1, paddingVertical: 0, color: palette.purpleDark, fontFamily: fonts.bodyMedium, fontSize: 18 },
  unit: { color: palette.textSecondary, fontFamily: fonts.body, fontSize: 12 },
  dropdown: { marginTop: 7, minHeight: 44, borderRadius: 12, borderColor: "rgba(183,154,197,0.55)", backgroundColor: "rgba(255,255,255,0.58)", paddingHorizontal: 12 },
  dropdownContainer: { borderRadius: radius.md, borderColor: palette.glassBorder, backgroundColor: palette.glass },
  dropdownText: { color: palette.purpleDark, fontFamily: fonts.bodyMedium, fontSize: 13 },
  cicloControls: { height: 46, marginTop: 7, paddingHorizontal: 4, borderWidth: 1, borderColor: "rgba(183,154,197,0.55)", borderRadius: radius.pill, backgroundColor: "rgba(255,255,255,0.58)", flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  cicloButton: { width: 38, height: 38, borderRadius: 19, backgroundColor: palette.purple, alignItems: "center", justifyContent: "center" },
  cicloButtonText: { color: palette.white, fontFamily: fonts.body, fontSize: 23, lineHeight: 25 },
  cicloValor: { color: palette.purpleDark, fontFamily: fonts.bodyMedium, fontSize: 16 },
  dateButton: { height: 44, marginTop: 7, paddingHorizontal: 12, borderWidth: 1, borderColor: "rgba(183,154,197,0.55)", borderRadius: 12, backgroundColor: "rgba(255,255,255,0.58)", flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  dateButtonText: { color: palette.purpleDark, fontFamily: fonts.bodyMedium, fontSize: 15 },
  imcCard: { borderColor: "rgba(114,142,69,0.28)", backgroundColor: "rgba(247,250,241,0.92)", alignItems: "center" },
  imcIcon: { backgroundColor: palette.mist },
  imcResult: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8, marginTop: 6, paddingVertical: 6, paddingHorizontal: 10, borderRadius: 12, backgroundColor: "rgba(231,236,217,0.72)" },
  imcValue: { color: palette.sageDark, fontFamily: fonts.bodyMedium, fontSize: 21 },
  imcBadge: { backgroundColor: "rgba(168,191,90,0.22)", borderRadius: radius.pill, paddingHorizontal: 10, paddingVertical: 6 },
  imcBadgeText: { color: palette.sageDark, fontFamily: fonts.bodyMedium, fontSize: 10 },
  saveButton: { height: 50, borderRadius: radius.pill, backgroundColor: palette.purpleDark, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 9, marginTop: 5, ...elevation.hero },
  saveButtonText: { color: palette.textOnDark, fontFamily: fonts.bodySemiBold, fontSize: 15 },
  sairContaButton: { height: 44, borderRadius: radius.pill, borderWidth: 1, borderColor: "rgba(86,53,92,0.35)", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, marginTop: 10 },
  sairContaTexto: { color: palette.purpleDark, fontFamily: fonts.bodyMedium, fontSize: 14 },
  excluirContaButton: { flexDirection: "row", alignItems: "center", justifyContent: "center", alignSelf: "center", gap: 7, marginTop: 19, paddingVertical: 10, paddingHorizontal: 16 },
  excluirContaTexto: { color: palette.error, fontFamily: fonts.body, fontSize: 14, textDecorationLine: "underline" },
});
