import { Platform, StyleSheet } from "react-native";
import { fonts } from "../../theme/fonts";
import { palette } from "../../theme/colors";

export const replicaStyles = StyleSheet.create({
  safeArea: { flex: 1 },
  drawerOverlay: { flex: 1, backgroundColor: "rgba(45,29,49,.32)" },
  drawer: { width: "76%", height: "100%", backgroundColor: "#FBF7F3", paddingTop: 72, paddingHorizontal: 28, borderTopRightRadius: 28, borderBottomRightRadius: 28 },
  drawerBrand: { fontFamily: fonts.title, fontSize: 38, color: palette.purpleDark, marginBottom: 24 },
  drawerItem: { flexDirection: "row", alignItems: "center", gap: 15, paddingVertical: 17, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: "#E6DCE5" },
  drawerText: { fontFamily: fonts.bodyMedium, fontSize: 16, color: palette.purpleDark },
  drawerLogout: { marginTop: "auto", borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: "#E6DCE5", borderBottomWidth: 0, marginBottom: 18 },
  drawerLogoutText: { color: palette.error },
  header: { height: 72, paddingHorizontal: 17, paddingTop: Platform.OS === "android" ? 12 : 4, paddingBottom: 4, flexDirection: "row", alignItems: "center", justifyContent: "space-between", backgroundColor: "rgba(255,252,250,.78)" },
  headerCompact: { height: 90, paddingHorizontal: 14, paddingTop: Platform.OS === "android" ? 20 : 8 },
  headerButton: { padding: 4 },
  headerActions: { flexDirection: "row", alignItems: "center", gap: 6 },
  headerActionsCompact: { gap: 4 },
  brand: { position: "absolute", left: 75, right: 75, top: Platform.OS === "android" ? 8 : 2, alignItems: "center", pointerEvents: "none" },
  brandCompact: { top: Platform.OS === "android" ? 25 : 14 },
  brandName: { fontFamily: fonts.title, fontSize: 32, lineHeight: 36, color: palette.purpleDark, letterSpacing: -1 },
  brandNameCompact: { fontSize: 29, lineHeight: 34 },
  brandTagline: { fontFamily: fonts.bodyMedium, fontSize: 6, letterSpacing: 2.2, color: "#8E7B98" },
  content: { paddingHorizontal: 17, paddingTop: 4, paddingBottom: 74, gap: 8 },
  hero: { height: 226, borderRadius: 22, overflow: "hidden", backgroundColor: "#FBF4FA", borderWidth: 1, borderColor: "#E9DDEA", paddingHorizontal: 20, paddingVertical: 14, shadowColor: palette.purpleDark, shadowOffset: { width: 0, height: 5 }, shadowOpacity: .05, shadowRadius: 14, elevation: 2 },
  heroWatermark: { position: "absolute", right: -75, top: -45, opacity: .65 },
  heroRow: { flexDirection: "row", flex: 1 },
  heroRowCompact: { flexDirection: "column" },
  heroCopy: { flex: 1, zIndex: 1, paddingRight: 4 },
  phaseLabelRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  phaseLabel: { fontFamily: fonts.title, fontSize: 16, color: palette.purpleDark },
  loader: { alignSelf: "flex-start", marginVertical: 22 },
  phaseName: { fontFamily: fonts.title, fontSize: 36, lineHeight: 40, color: "#719066", marginTop: 3 },
  phaseNameCompact: { fontSize: 39, lineHeight: 47 },
  phaseMood: { fontFamily: fonts.body, fontSize: 15, color: "#714477", marginTop: 0 },
  phaseDescription: { fontFamily: fonts.body, fontSize: 12, lineHeight: 16, color: "#82758D", marginTop: 5, maxWidth: 220 },
  primaryButton: { marginTop: "auto", width: 166, height: 44, borderRadius: 22, backgroundColor: palette.purple, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 11 },
  primaryButtonCompact: { width: "100%", marginTop: 16 },
  primaryButtonText: { fontFamily: fonts.bodyBold, fontSize: 15, color: "#fff" },
  heroSide: { width: 140, alignItems: "center", justifyContent: "space-between", paddingTop: 17 },
  heroSideCompact: { width: "100%", flexDirection: "row", justifyContent: "space-between", paddingTop: 22 },
  cycleRing: { width: 96, height: 96, borderRadius: 48, borderWidth: 10, borderColor: "#EBD9E9", borderTopColor: "#AE4F94", borderRightColor: "#AE4F94", alignItems: "center", justifyContent: "center", transform: [{ rotate: "-12deg" }] },
  cycleRingCompact: { width: 108, height: 108, borderRadius: 54, borderWidth: 13 },
  cycleSmall: { fontFamily: fonts.body, fontSize: 13, color: "#745278", transform: [{ rotate: "12deg" }] },
  cycleDay: { fontFamily: fonts.bodyBold, fontSize: 24, lineHeight: 26, color: palette.purpleDark, transform: [{ rotate: "12deg" }] },
  nextPhase: { width: 140, height: 44, paddingHorizontal: 12, borderRadius: 22, borderWidth: 1, borderColor: "#E4D4E4", backgroundColor: "rgba(255,255,255,.82)", flexDirection: "row", alignItems: "center", gap: 7 },
  nextPhaseCompact: { width: 150, marginTop: 0, paddingHorizontal: 9, gap: 5 },
  nextPhaseCopy: { flex: 1, justifyContent: "center" },
  nextPhaseLabel: { fontFamily: fonts.body, fontSize: 11, lineHeight: 13, color: "#765D80" },
  nextPhaseValue: { fontFamily: fonts.bodyBold, fontSize: 13, lineHeight: 16, color: palette.purpleDark },
  activityCard: { minHeight: 124, borderRadius: 20, backgroundColor: "rgba(255,253,251,.9)", borderWidth: 1, borderColor: "#E6DCE8", padding: 14, flexDirection: "row", alignItems: "center", gap: 12 },
  activityCardCompact: { flexDirection: "column", alignItems: "stretch", gap: 14, padding: 16 },
  activityMain: { flex: 1, flexDirection: "row", alignItems: "flex-start", gap: 12 },
  roundIcon: { width: 52, height: 52, borderRadius: 26, alignItems: "center", justifyContent: "center", flexShrink: 0 },
  activityCopy: { flex: 1, minWidth: 0 },
  activityTitle: { fontFamily: fonts.title, fontSize: 17, lineHeight: 20, color: palette.purpleDark },
  activitySubtitle: { fontFamily: fonts.body, fontSize: 11, color: "#625982", marginTop: 1 },
  metaRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", columnGap: 10, rowGap: 3, marginTop: 5 },
  metaItem: { flexDirection: "row", alignItems: "center", gap: 4 },
  metaText: { fontFamily: fonts.body, fontSize: 10, color: "#655B83" },
  activityDescription: { fontFamily: fonts.body, fontSize: 10, lineHeight: 14, color: "#796D8C", marginTop: 4 },
  // Mesmo formato do "Saiba mais" do topo: pílula com texto e seta dentro.
  activityButton: { flexShrink: 0, height: 40, paddingHorizontal: 14, borderRadius: 20, backgroundColor: palette.purple, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  activityButtonCompact: { height: 44, borderRadius: 22 },
  activityButtonText: { fontFamily: fonts.bodyBold, fontSize: 13, color: "#fff" },
  // Cartão da rotina: mesma casca dos cartões desta Home, com altura livre
  // porque a legenda cresce quando há próxima dose e barra de água.
  // Faixa do teste grátis: só existe com a cobrança ligada.
  trialAviso: { flexDirection: "row", alignItems: "center", gap: 9, borderRadius: 16, paddingVertical: 11, paddingHorizontal: 13, backgroundColor: "#FDF3DC", borderWidth: 1, borderColor: "#EBD9AE" },
  trialTexto: { flex: 1, fontFamily: fonts.bodyMedium, fontSize: 12, color: "#6B4B06" },
  trialAcao: { fontFamily: fonts.bodyBold, fontSize: 12, color: palette.purpleDark },
  rotinaCard: { borderRadius: 20, backgroundColor: "rgba(255,253,251,.9)", borderWidth: 1, borderColor: "#E6DCE8", padding: 12 },
  progressCard: { minHeight: 126, borderRadius: 20, backgroundColor: "rgba(255,253,251,.9)", borderWidth: 1, borderColor: "#E6DCE8", paddingHorizontal: 14, paddingTop: 12, paddingBottom: 13 },
  progressCardCompact: { minHeight: 146, paddingBottom: 14 },
  progressHeader: { flexDirection: "row", alignItems: "center", gap: 13 },
  progressHeaderCompact: { flexWrap: "wrap" },
  progressTitle: { flex: 1, fontFamily: fonts.title, fontSize: 16, color: palette.purpleDark },
  progressValue: { fontFamily: fonts.body, fontSize: 10, color: "#5D527C" },
  progressTrack: { height: 8, borderRadius: 8, backgroundColor: "#EDE4F1", overflow: "hidden", marginLeft: 65, marginTop: 8 },
  progressTrackCompact: { marginLeft: 0, marginTop: 12 },
  progressFill: { height: "100%", borderRadius: 8, backgroundColor: "#92528C" },
  weekRow: { flexDirection: "row", justifyContent: "space-between", marginLeft: 62, marginTop: 10 },
  weekRowCompact: { marginLeft: 0 },
  weekDay: { alignItems: "center", gap: 5 },
  dayCircle: { width: 21, height: 21, borderRadius: 11, borderWidth: 1.5, borderColor: "#C9C0D0", alignItems: "center", justifyContent: "center" },
  dayCircleActive: { backgroundColor: palette.purple, borderColor: palette.purple },
  dayText: { fontFamily: fonts.body, fontSize: 9, color: "#756A87" },
  rewardCard: { height: 100, borderRadius: 20, backgroundColor: "#F0F2E8", borderWidth: 1, borderColor: "#E0E3D5", padding: 11, flexDirection: "row", alignItems: "center", gap: 12, overflow: "hidden" },
  rewardCardCompact: { gap: 12, paddingHorizontal: 14 },
  moonOrbit: { width: 82, height: 78, borderRadius: 42, borderWidth: 1, borderColor: "#C7CEAE", alignItems: "center", justifyContent: "center" },
  moonImage: { width: 57, height: 57, resizeMode: "contain" },
  rewardCopy: { flex: 1 },
  points: { fontFamily: fonts.title, fontSize: 18, color: "#987014" },
  className: { fontFamily: fonts.title, fontSize: 15, color: palette.purpleDark, marginTop: 1 },
  rewardCaption: { fontFamily: fonts.body, fontSize: 10, color: "#9B9A86", marginTop: 3 },
  quoteRow: { height: 23, flexDirection: "row", alignItems: "center", gap: 12, paddingHorizontal: 22 },
  quoteLine: { flex: 1, height: 1, backgroundColor: "#D4CBD4" },
  quote: { fontFamily: fonts.bodyMedium, fontSize: 9, letterSpacing: 2.2, color: "#938398" },
  bottomNav: { position: "absolute", left: 0, right: 0, bottom: 0, height: 70, paddingBottom: Platform.OS === "ios" ? 7 : 2, borderTopLeftRadius: 24, borderTopRightRadius: 24, backgroundColor: "rgba(255,253,252,.98)", flexDirection: "row", alignItems: "center", justifyContent: "space-around", borderTopWidth: 1, borderTopColor: "#EEE6ED", shadowColor: palette.purpleDark, shadowOffset: { width: 0, height: -5 }, shadowOpacity: .05, shadowRadius: 18, elevation: 12 },
  navItem: { flex: 1, height: 60, alignItems: "center", justifyContent: "center", gap: 1 },
  navText: { fontFamily: fonts.body, fontSize: 11, color: "#706687" },
  navTextActive: { fontFamily: fonts.bodyBold, color: palette.purpleDark },
  navDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: palette.purpleDark, marginTop: 2 },
});
